Random generator
GazePlay/GazePlay pull request #1168
Opened 2020-04-02 16:33 UTC by christophezei

- Added Random Generator class.
-Copied Creampie game .
-Applied our random lib functions on creampies copy (chrispie) located under creampie dir.

2020-04-03 08:20 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/random/Random.java
> +    private double m;
Can you please give more explicit name to the a (multiplier), c (incrementer) and m (modulus) variable please ? :)

2020-04-03 08:26 UTC, kuhlkrein commented on gazeplay-games-commons/src/main/java/net/gazeplay/components/PortraitTest.java
> +public class PortraitTest extends Circle {
If this class was just for testing please remove it from your PR you're done with testing

2020-04-03 08:26 UTC, kuhlkrein commented on gazeplay-games-commons/src/main/java/net/gazeplay/IGameContext.java
> +import net.gazeplay.components.RandomPositionGeneratorGazePlayRandomLib;
If this class was just for testing please remove it from your PR you're done with testing

2020-04-03 08:29 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/creampie/Hand.java
> +
please remove blank space

2020-04-03 08:30 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/creampie/Target.java
> +
please remove blank space

2020-04-03 08:30 UTC, kuhlkrein commented on gazeplay/src/main/java/net/gazeplay/commons/utils/RandomPanePositionGeneratorTest.java
> +public class RandomPanePositionGeneratorTest extends RandomPositionGeneratorGazePlayRandomLib {
If this class was just for testing please remove it from your PR you're done with testing

2020-04-03 08:31 UTC, kuhlkrein commented on gazeplay/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java
> +    private final RandomPositionGeneratorGazePlayRandomLib randomPositionGeneratorGazePlayLib;
If this class was just for testing please remove it from your PR you're done with testing

2020-04-03 08:47 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/random/Random.java
> +    public int randNumberRange(double max, double min){
It's really good to have this int function, but we also need a double function. The Math.random() function is for instance returning a number between 0 and 1, and this function can be really usefull sometimes. It would be good to have it also :). Also, if you manage to create this random() function you can then implement your randIntRange(min,max) just by Min + (int)(Math.random() * ((Max - Min) + 1))

2020-04-03 08:56 UTC, kuhlkrein commented
Looks like you have some PMD error, you can check it by building gazeplay on your local machine (with ./gradlew build on linux or gradle build on windows), you can see the meaning of the code issue here : https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html

2020-04-03 11:21 UTC, YannRobert commented on gazeplay-commons/src/main/java/net/gazeplay/commons/random/Random.java
> +        seed = (a * seed + c) % m;
So this is not really random !
Is there a formula for random ?

2020-04-03 11:22 UTC, YannRobert commented on gazeplay-commons/src/main/java/net/gazeplay/commons/random/Random.java
> +public class Random {
I don't understand the need for this class a there is already plenty existing things to do random in Java API and even if this is not enough there are also plenty of existing third party libs.

2020-04-03 11:25 UTC, YannRobert commented on gazeplay/src/main/java/net/gazeplay/commons/utils/RandomPanePositionGeneratorTest.java
> +public class RandomPanePositionGeneratorTest extends RandomPositionGeneratorGazePlayRandomLib {
Is this a unit test or what is this ?

2020-04-03 11:27 UTC, YannRobert commented on gazeplay/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java
> +        this.randomPositionGeneratorGazePlayLib = new RandomPanePositionGeneratorTest(gamePanelDimensionProvider);
Is this an alternative implementation of the existing RandomPanPositionGenerator ?
Why not implement the same interface and inject it as the randomPositionGenerator directly ?

2020-04-06 08:33 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/random/ReplayablePseudoRandom.java
> +    public int randIntRange(double max, double min){
Can you please invert min and max ? usually min is first in the parameters

2020-04-09 11:41 UTC, kuhlkrein commented on gazeplay-games-commons/src/main/java/net/gazeplay/components/RandomPositionGenerator.java
> +            final double positionX = random.randIntRange(maxX, maxY);
Here, it have to be minX

2020-04-14 13:49 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/random/ReplayablePseudoRandom.java
> +        return this.random() / (double)RAND_MAX ;
why  are you using / instead of % here ?

2020-04-14 13:51 UTC, kuhlkrein commented
Can you please have a look at the PMD violations related to your files ?

2020-04-14 13:56 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/random/ReplayablePseudoRandom.java
> +    /*
Please add space before the specification and don't forget to reformat code

2020-04-14 13:57 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/random/ReplayablePseudoRandom.java
> +        return this.random() / (double)RAND_MAX ;
why are you using / instead of % here ?

2020-05-26 09:37 UTC, kuhlkrein commented
there are still errors with gradle:

```
/home/runner/work/GazePlay/GazePlay/gazeplay-games/src/main/java/net/gazeplay/games/moles/Moles.java:141: error: method nextInt in class ReplayablePseudoRandom cannot be applied to given types;
                int n = r.nextInt();
                         ^
  required: int
  found: no arguments
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

2020-07-02 10:12 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/random/ReplayablePseudoRandom.java
> +        int RAND_MAX = Integer.MAX_VALUE;
to delete spotbugs error please rename by rand_max

2020-07-02 10:12 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/random/ReplayablePseudoRandom.java
> +        int RAND_MAX = Integer.MAX_VALUE;
(same) to delete spotbugs error please rename by rand_max

2020-07-03 11:58 UTC, kuhlkrein commented
@christophezei I think there is a problem with the random functions because I have some issue in some specific games:

+ biboule jump:
no bouncing plateforme on animated version

+ cake:
cake color is always the same, deco topping too

+ gobelet pass pass:
movement are always the same ( at least on 3 *3), right gobelet never move

+ pet game: (not a big deal)
ball always come from left side

2020-08-27 09:24 UTC, kuhlkrein approved these changes

2020-08-27 12:57 UTC, kuhlkrein commented
@schwabdidier @YannRobert @Tohaker any objection before merging? :)

2020-08-27 13:07 UTC, Tohaker requested changes

2020-08-27 13:07 UTC, Tohaker commented on gazeplay-commons/src/test/java/net/gazeplay/commons/random/ReplayablePseudoRandomTest.java
> +    public void nextIntTest()
These aren't tests - you need to make assertions so the test suite can determine if they pass. Please remove the logging and use the `assertX` methods in JUnit.

2020-08-27 13:08 UTC, Tohaker commented
Give me some time to read through it, but the testing needs to be done properly. I appreciate that they were considered, at least.

2020-08-27 14:28 UTC, Tohaker requested changes

2020-08-27 14:28 UTC, Tohaker commented on gazeplay-games-commons/src/main/java/net/gazeplay/components/Portrait.java
>          // int index = (int) (count * Math.random());
I know you didn't put this in, but it's good practice to tidy files up as you go along.

2020-08-27 14:28 UTC, Tohaker commented on gazeplay-games-commons/src/main/java/net/gazeplay/components/RandomPositionGenerator.java
> +            final double positionY =  random.nextInt((int) ((maxY-minY + 1) + minY));
Could you format these lines please? Just keeps it all neat!

2020-08-27 14:28 UTC, Tohaker commented on gazeplay-games/src/main/java/net/gazeplay/games/cups/utils/Strategy.java
> +        final ReplayablePseudoRandom randomGenerator = new ReplayablePseudoRandom();
Why not just use the same one in the class?

2020-08-27 14:37 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/cups/utils/Strategy.java
> +        final ReplayablePseudoRandom randomGenerator = new ReplayablePseudoRandom();
Oh yes I forgot to remove thank you

2020-08-27 14:39 UTC, kuhlkrein commented on gazeplay-commons/src/test/java/net/gazeplay/commons/random/ReplayablePseudoRandomTest.java
> +    public void nextIntTest()
Sure, I'll add a test with a bigger loop and check if the results are near too each others

2020-08-28 22:24 UTC, Tohaker approved these changes
Looks great now, thanks for sorting out the tests!

2020-09-01 08:43 UTC, merged