trying to add all coord by firing event to root
GazePlay/GazePlay pull request #1223
Opened 2020-08-26 07:51 UTC by Adrieennn

not working after resize

2020-08-27 14:42 UTC, kuhlkrein commented
SpotBug issue:

```
  <BugInstance type="RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE" priority="2" rank="18" abbrev="RCN" category="STYLE">
    <Class classname="net.gazeplay.commons.gaze.devicemanager.AbstractGazeDeviceManager">
      <SourceLine classname="net.gazeplay.commons.gaze.devicemanager.AbstractGazeDeviceManager" start="26" end="259" sourcefile="AbstractGazeDeviceManager.java" sourcepath="net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java"/>
    </Class>
    <Method classname="net.gazeplay.commons.gaze.devicemanager.AbstractGazeDeviceManager" name="eventFire" signature="(DDLnet/gazeplay/commons/gaze/devicemanager/GazeInfos;Ljavafx/scene/Node;)V" isStatic="false">
      <SourceLine classname="net.gazeplay.commons.gaze.devicemanager.AbstractGazeDeviceManager" start="220" end="259" startBytecode="0" endBytecode="293" sourcefile="AbstractGazeDeviceManager.java" sourcepath="net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java"/>
    </Method>
    <LocalVariable name="localPosition" register="7" pc="19" role="LOCAL_VARIABLE_VALUE_OF"/>
    <Method classname="javafx.geometry.Point2D" name="&lt;init&gt;" signature="(DD)V" isStatic="false" role="METHOD_RETURN_VALUE_OF">
      <SourceLine classname="javafx.geometry.Point2D" start="84" end="87" startBytecode="0" endBytecode="59" sourcefile="Point2D.java" sourcepath="javafx/geometry/Point2D.java"/>
    </Method>
    <SourceLine classname="net.gazeplay.commons.gaze.devicemanager.AbstractGazeDeviceManager" start="244" end="244" startBytecode="114" endBytecode="114" sourcefile="AbstractGazeDeviceManager.java" sourcepath="net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java" role="SOURCE_REDUNDANT_NULL_CHECK"/>
  </BugInstance>
```

2020-08-28 09:25 UTC, kuhlkrein requested changes

2020-08-28 09:25 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java
> -            Point2D localPosition = node.screenToLocal(positionX, positionY);
I think it would be better to keep the regular eventFire and to create a specific one for the GameScene

2020-08-28 09:25 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java
>              if (localPosition != null && node.contains(localPosition)) {
in the eventFireGameScene function you can also remove the localPosition != null here

2020-08-28 09:25 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java
> +                        firedToRoot = true;
why do you need this ?

2020-08-28 09:25 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java
> +        fireCount = 0;
I think this value is never used, it's for testing right ?

2020-08-28 11:09 UTC, Adrieennn commented on gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java
> +        fireCount = 0;
yes I'll remove this

2020-09-07 08:33 UTC, kuhlkrein requested changes

2020-09-07 08:33 UTC, kuhlkrein commented on gazeplay-core/src/test/java/net/gazeplay/ui/scenes/ingame/GameContextTest.java
> +        when(mockStats.getFixationSequence()).thenReturn(new ArrayList<>(List.of(new LinkedList<>(), new LinkedList<>())));
@Tohaker is it ok to test like this ?

2020-09-07 08:37 UTC, Tohaker commented on gazeplay-core/src/test/java/net/gazeplay/ui/scenes/ingame/GameContextTest.java
> +        when(mockStats.getFixationSequence()).thenReturn(new ArrayList<>(List.of(new LinkedList<>(), new LinkedList<>())));
Yes, this is fine if you need to mock this response. However, this doesn't assert anything in case you're thinking this line is a test itself.

2020-09-07 09:38 UTC, kuhlkrein commented on gazeplay-core/src/test/java/net/gazeplay/ui/scenes/ingame/GameContextTest.java
> +        when(mockStats.getFixationSequence()).thenReturn(new ArrayList<>(List.of(new LinkedList<>(), new LinkedList<>())));
Yes of course, actually it's because when I initialize one of the parameters in the stats function, it seems that it's not initialized in the mockStats, so I need this to avoid the nullpointer

2020-09-15 14:25 UTC, kuhlkrein commented
Hello @Tohaker , @YannRobert this should be ready for reviews, I tested it and reviewed several times after @Adrieennn 's implementation

2020-09-15 17:07 UTC, Tohaker requested changes

2020-09-15 17:07 UTC, Tohaker commented on gazeplay-core/src/main/java/net/gazeplay/ui/scenes/stats/StatsContext.java
> +        displayMouseAndGazeButton.setOnMouseClicked((e) -> {
This repetitive code can be extracted to its own method.

2020-09-15 17:07 UTC, Tohaker commented on gazeplay-games/src/main/java/net/gazeplay/games/rushhour/Car.java
> +        gameContext.getGazeDeviceManager().addEventFilter(this);
Everything else is `addStats`, is this correct?

2020-09-16 07:58 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/rushhour/Car.java
> +        gameContext.getGazeDeviceManager().addEventFilter(this);
Yes it's a different function here, a fix for rushHour :)

2020-09-16 08:01 UTC, kuhlkrein commented on gazeplay-core/src/main/java/net/gazeplay/ui/scenes/stats/StatsContext.java
> +        displayMouseAndGazeButton.setOnMouseClicked((e) -> {
Yes, I was thinking about it but I was not sure it was worth it

2020-09-17 07:57 UTC, kuhlkrein commented
fix #1227

2020-09-17 17:01 UTC, Tohaker approved these changes

2020-09-18 07:55 UTC, kuhlkrein approved these changes

2020-09-18 14:54 UTC, kuhlkrein commented
fix #1225

2020-09-22 08:09 UTC, merged