-created a dialog for error handling in WhereIsIt game when dir is no…
GazePlay/GazePlay pull request #1229
Opened 2020-09-10 11:09 UTC by christophezei

…t configured (#1175)

-added option to configure WhereIsIt dir in the new dialog created.
-fixed pmd violation in StatContextTest

2020-09-11 14:13 UTC, kuhlkrein requested changes

2020-09-11 14:13 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/whereisit/WhereIsIt.java
> +
please remove this space

2020-09-11 14:13 UTC, kuhlkrein commented on gazeplay-games-commons/src/main/java/net/gazeplay/commons/gamevariants/generators/IGameVariantGenerator.java
> +
please remove the spaces added

2020-09-11 14:13 UTC, kuhlkrein commented on gazeplay-core/src/test/java/net/gazeplay/ui/scenes/stats/StatsContextTest.java
> +    void shouldAddAllToGridShootGames(boolean alignLeft) {
Why did you change the name of these functions ?

2020-09-11 14:49 UTC, christophezei commented on gazeplay-core/src/test/java/net/gazeplay/ui/scenes/stats/StatsContextTest.java
> +    void shouldAddAllToGridShootGames(boolean alignLeft) {
Pmd error i mentioned in the commit.

2020-09-16 14:49 UTC, kuhlkrein commented
Where is it dialog is displayed when choosing the variant of any game, please make it appear only when trying to open custom where is it

2020-09-16 14:54 UTC, kuhlkrein requested changes

2020-09-16 14:54 UTC, kuhlkrein commented on gazeplay-core/src/main/java/net/gazeplay/ui/scenes/gamemenu/GameVariantDialog.java
> +                if(config.getWhereIsItDir().equals("")) {
add && gameSpec.getGameSummary().getNameCode().equals("WhereIsIt")) here to be sure to display the dialog only if we're trying to open custom where is it

2020-09-16 19:27 UTC, christophezei commented on gazeplay-core/src/main/java/net/gazeplay/ui/scenes/gamemenu/GameVariantDialog.java
> +                if(config.getWhereIsItDir().equals("")) {
fixed:)

2020-09-21 09:53 UTC, kuhlkrein requested changes

2020-09-21 09:53 UTC, kuhlkrein commented on gazeplay-core/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java
> +    public ConfigurationContext(GazePlay gazePlay) {
Doesn't need to be public as the GameErrorDialog is only for where is it game

2020-09-21 09:53 UTC, kuhlkrein commented on gazeplay-core/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java
> +    public enum DirectoryType {
same

2020-09-21 09:53 UTC, kuhlkrein commented on gazeplay-core/src/main/java/net/gazeplay/ui/scenes/errorhandlingui/GameErrorDialog.java
> +        final ConfigurationContext configurationContext,
configurationContext is not necessarry as we already have gazePlay

2020-09-21 09:53 UTC, kuhlkrein commented on gazeplay-core/src/main/java/net/gazeplay/ui/scenes/gamemenu/GameVariantDialog.java
>          // scene.getStylesheets().add(getClass().getResource("modal-dialog.css").toExternalForm());
I guess we could delete this comment

2020-09-24 07:24 UTC, kuhlkrein commented
Any modification needed @Tohaker ? :)

2020-09-24 07:45 UTC, Tohaker requested changes
Looking very good! Just one change to keep the code simple and we're good to go :smile:

2020-09-24 07:45 UTC, Tohaker commented on gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/WhereIsItVaildator.java
> +                        while (!containsImage && i < filesInf.length) {
This can definitely be simplified to a for-each loop that breaks when it finds an image.

2020-10-02 07:47 UTC, Tohaker approved these changes

2020-10-15 13:44 UTC, kuhlkrein approved these changes

2020-10-15 13:44 UTC, merged