Remplacement des labels
GazePlay/GazePlay pull request #1310
Opened 2021-02-12 14:39 UTC by Noars

- "Ficher de style" par "Palette de couleurs";
- "Style de fond" par "Couleur de fond des jeux";

2021-02-13 13:39 UTC, schwabdidier commented
"Arrière-plan" would be better than "fond"

2021-02-18 14:35 UTC, kuhlkrein commented
J'aurai peut être laissé style d'arrière plan pour le moment comme les valeurs possible sont "clair" et "sombre"

2021-03-16 15:36 UTC, kuhlkrein requested changes

2021-03-16 15:36 UTC, kuhlkrein commented on gazeplay-commons/src/test/resources/data/multilinguism/multilinguism.csv
> +BackgroundStyle,,,,,,Background style,,Couleur de l'arrière-plan des jeux,,,,,,,,,,,
please keep "style" instead of couleur because for now we're provided only light/dark themes

2021-05-21 14:26 UTC, kuhlkrein commented
@Noars

2021-07-06 09:54 UTC, kuhlkrein approved these changes

2021-07-06 09:55 UTC, merged