Dwell time fixation zero duration
GazePlay/GazePlay pull request #1333
Opened 2021-03-04 12:32 UTC by Noars

It's a Pull Request for the issue #1318

2021-03-04 15:58 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/creampie/Target.java
> +        /*timeline.getKeyFrames()
Tu as totalement enlevé cette partie de l'animation ?

2021-03-04 15:58 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/creampie/Target.java
> +        setLayoutX(newPosition.getX());
you just assigned this.centerX and Y with these values, maybe you should use setLayout(this.centerX) instead

2021-03-04 15:58 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/moles/MolesChar.java
> +        this.progressIndicator = createProgressIndicator();
is this indicator still relevant ?

2021-03-04 15:58 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/ninja/Target.java
> +            final ProgressPortrait miniProgressPortrait = new ProgressPortrait();
Here I think you only need Portraits, they don't have to be progressPortrait, I think progressPortrait are taking more space in the java heap map, it could be better to keep classic portrait objects

2021-03-04 15:58 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/pianosight/Piano.java
> +        switch (index) {
Have you tested it for different screen size ?
Otherwise we'll may have to use cos and sin to have more accurate values

2021-03-05 16:17 UTC, Noars commented on gazeplay-games/src/main/java/net/gazeplay/games/moles/MolesChar.java
> +        this.progressIndicator = createProgressIndicator();
Yes, it is still relevant. 
It is used to make the biboule come out of the ground.

2021-03-08 08:30 UTC, kuhlkrein requested changes

2021-03-08 08:30 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/moles/MolesChar.java
> +        this.progressIndicator = createProgressIndicator();
Can you please instead use 

```
 DoubleProperty timeOut = new SimpleDoubleProperty(0);
            timeMoleOut = new Timeline(); // New time this mole go out
            final int time = random.nextInt(timeMoleStayOut) + 2000;

            timeMoleOut.getKeyFrames()
                .add(new KeyFrame(new Duration(time),
                    new KeyValue(timeOut, 1)));
            timeMoleOut.rateProperty().bind(gameContext.getAnimationSpeedRatioSource().getSpeedRatioProperty());
```

at line 154 ?
ProgressIndicator are items created to be displayed, and we should not use it only for it's progressProperty

2021-03-08 09:14 UTC, Noars commented on gazeplay-games/src/main/java/net/gazeplay/games/pianosight/Piano.java
> +        switch (index) {
I just tested with different screen sizes and it still works without problem, progressIndicator is always in the right place.

2021-03-08 15:27 UTC, kuhlkrein requested changes

2021-03-08 15:27 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/pianosight/Piano.java
> +                this.progressIndicator = createProgressIndicator(index, size, dimension2D);
Please set progressIndicator mouseTransparency to true otherwise it will trigger the exit event for tile objects

2021-03-09 09:04 UTC, kuhlkrein approved these changes
Looks good to me, ready to merge.

2021-03-09 09:40 UTC, kuhlkrein requested changes
Looks good to me, ready to merge.

2021-03-09 09:40 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java
> +    public void setFixationLength(final int fixationLength) { fixationlengthProperty.setValue(fixationLength); }
There is an issue with fixation length property. I think games like ninja or creampie should not update the default fixation lentgh value. Also when going back to the configuration context it looks like the dwell_time value is not always correctly updated

2021-05-21 15:07 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java
> +    public void setFixationLength(final int fixationLength) { fixationlengthProperty.setValue(fixationLength); }
@Noars can you please check that ?

2021-07-07 14:17 UTC, kuhlkrein commented on gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java
> +    public void setFixationLength(final int fixationLength) { fixationlengthProperty.setValue(fixationLength); }
not sure of this request

2021-07-08 08:04 UTC, kuhlkrein commented
please cancel the last revert, it looks like it's deleting a lot of new code

2021-07-13 14:55 UTC, kuhlkrein approved these changes

2021-07-13 14:58 UTC, kuhlkrein requested changes
Needs to update the fixation time property

2021-07-16 12:25 UTC, kuhlkrein approved these changes

2021-07-16 12:25 UTC, merged