we can lose in the game FrogRace now
GazePlay/GazePlay pull request #1353
Opened 2021-05-10 09:43 UTC by PillouMatou

The game is lost when you finish last issue #1314

2021-05-21 07:27 UTC, Noars approved these changes
After several tests, it works without problem !
I made sure to lose several times in a row (5 times) then win. I saw no problem

2021-05-21 07:27 UTC, Noars commented on gazeplay-games/src/main/java/net/gazeplay/games/race/Race.java
> +            if(numberOfRacerFinished == 3) {
Si une grenouille IA fini, le joueur a déjà perdu, donc pas besoin d'attendre que les 2 autres grenouilles IA finissent autant reset le jeu directement au lieu d'attendre ?

2021-07-01 11:36 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/race/Race.java
> +            if(numberOfRacerFinished == 3) {
En plus avec l'implémentation actuelle , si le joueur arrive avant une autre grenouille (donc deuxième ou troisième), on n'attend pas la dernière, donc oui je suis d'accord, autant reset direct

2021-07-01 12:05 UTC, kuhlkrein requested changes

2021-07-01 12:05 UTC, kuhlkrein commented on gazeplay-commons/src/main/resources/logback.xml
> +    <logger name="org.springframework" level="ALL"/>
please reset the OFF value

2021-07-05 08:30 UTC, PillouMatou commented on gazeplay-games/src/main/java/net/gazeplay/games/race/Race.java
> +            if(numberOfRacerFinished == 3) {
j'ai testé de finir genre entre 2ème et 3ème, je me retrouve encore une fois avec les transitions qui font tout planter et pas moyen de les stopper.

2021-07-05 12:52 UTC, kuhlkrein requested changes

2021-07-05 12:52 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/race/Race.java
> +                racers[0].t.stop();
please put the stop before calling playwintransition or the oponent frogs can stop the game during the win transition

2021-07-07 13:23 UTC, kuhlkrein approved these changes

2021-07-07 13:42 UTC, merged