Mouse event triggered at game launch #1339
GazePlay/GazePlay pull request #1354
Opened 2021-05-10 14:31 UTC by Iluvrog

The delay can be adjusted

2021-05-14 13:27 UTC, PillouMatou approved these changes
The function seems to work well. The function that overloads with an adjustable delay is not called yet so we can't test it but reading the code we can see that there should be no problems.

2021-07-01 11:57 UTC, kuhlkrein requested changes

2021-07-01 11:57 UTC, kuhlkrein commented on gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java
> +        int delay = 2000;
For now, you can let the onGameStarted() empty and use the onGameStarted(delay) in the game that needs it.
The current version has some issues because most of the games are not calling this function they are actually calling it when restarting the game, so the delay will apply only for the 2nd trial

2021-07-05 07:59 UTC, Iluvrog commented
@kuhlkrein it's done

2021-07-05 13:37 UTC, kuhlkrein commented
Perfect !
There are just two PMD errors to fix to make the tests pass:


-  /home/getalp/riouse/eclipse-workspace/GazePlayGeoffrey/gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java  -> The local variable name 'Wait' doesn't match '[a-z][a-zA-Z0-9]*'

-  /home/getalp/riouse/eclipse-workspace/GazePlayGeoffrey/gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java -> The lambda parameter name 'WaitEvent' doesn't match '[a-z][a-zA-Z0-9]*'

Actually just need to change first letter of each variable to lower case

2021-07-05 13:56 UTC, Iluvrog commented
> Perfect !
> There are just two PMD errors to fix to make the tests pass:
> 
> * /home/getalp/riouse/eclipse-workspace/GazePlayGeoffrey/gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java  -> The local variable name 'Wait' doesn't match '[a-z][a-zA-Z0-9]*'
> * /home/getalp/riouse/eclipse-workspace/GazePlayGeoffrey/gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java -> The lambda parameter name 'WaitEvent' doesn't match '[a-z][a-zA-Z0-9]*'
> 
> Actually just need to change first letter of each variable to lower case

it's done

2021-07-06 09:59 UTC, kuhlkrein approved these changes
Everything looks good to me

2021-07-06 09:59 UTC, merged