colorsgame not select right after starting
GazePlay/GazePlay pull request #1358
Opened 2021-05-12 08:06 UTC by Iluvrog

only work with the pull request #1354

2021-05-14 14:43 UTC, PillouMatou reviewed
if I understood correctly, we should not be able to draw when the game starts, except that on my side he draws right away with the red color

2021-05-17 06:36 UTC, Iluvrog commented
> if I understood correctly, we should not be able to draw when the game starts, except that on my side he draws right away with the red color

It only work with the pull request #1354 (don't work without)

2021-07-01 12:15 UTC, kuhlkrein requested changes

2021-07-01 12:15 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorsGame.java
> +        gameContext.onGameStarted();
Please then pull the changes given by  #1354 and add an explicit delay to onGameStarted

2021-07-05 07:08 UTC, closed without merging