Different type of bottles (idea from Jessica Martinez) #1253
GazePlay/GazePlay pull request #1360
Opened 2021-05-14 15:10 UTC by Iluvrog

Need a translation with the size name (like small, big ...)

2021-05-31 07:50 UTC, PillouMatou requested changes
It's fine for the functionnality.
Translate your buttons and we can merge I think. 👍

2021-06-02 13:08 UTC, Iluvrog commented
> It's fine for the functionnality.
> Translate your buttons and we can merge I think. 👍

translation done

2021-06-04 07:24 UTC, PillouMatou approved these changes
it's fine for me @kuhlkrein @schwabdidier

2021-07-01 12:51 UTC, kuhlkrein approved these changes

2021-07-01 12:51 UTC, merged