The cake factory, Normal and Extreme level #1297
GazePlay/GazePlay pull request #1362
Opened 2021-05-17 15:18 UTC by Iluvrog

you don't have a positive result if you not complete the cake in the normale and extreme mode

2021-05-31 07:40 UTC, PillouMatou requested changes
For the easy and normal mode it's alright, but normal and hard is the same difficult.
I think we should try to do a cake with 2 stages for the normal mode.

2021-06-02 13:38 UTC, Iluvrog commented
> For the easy and normal mode it's alright, but normal and hard is the same difficult.
> I think we should try to do a cake with 2 stages for the normal mode.

In the extreme mode, the cake disappear when the gaze (mouse) isn't on it.
And change the difficult of the mode isn't the goal and the issue and PR

2021-06-04 07:32 UTC, PillouMatou commented
> In the extreme mode, the cake disappear when the gaze (mouse) isn't on it.
> And change the difficult of the mode isn't the goal and the issue and PR

Ok it's fine for me then 👍  @kuhlkrein @schwabdidier

2021-07-02 08:13 UTC, kuhlkrein approved these changes

2021-07-02 08:13 UTC, merged