Dynamic Adaptation for Memory and Ninja games
GazePlay/GazePlay pull request #1363
Opened 2021-05-17 15:31 UTC by verafili

WIP, the menu selection for the Ninja game variant (static vs dynamic) has to be modified

2021-05-20 08:23 UTC, PillouMatou requested changes
jeu memory, le niveau 7 et 8 sont les mêmes et tu sautes du niveau 7 à 8 du coup, essaie d'enlever un des 2 niveaux.
jeu space, la fixation length ne sert pas dans ce jeu, on ne sélectionne rien, il faudrait le retirer du coup

2021-05-21 11:44 UTC, PillouMatou reviewed
ça à l'air d'être tout bon @kuhlkrein

2021-07-01 13:12 UTC, kuhlkrein requested changes

2021-07-01 13:12 UTC, kuhlkrein commented on gazeplay-commons/src/main/resources/logback.xml
> +    <logger name="org.springframework" level="INFO"/>
please put back the OFF value here

2021-07-01 13:12 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/memory/Memory.java
> +    public int getNbColumns() { return nbColumns; }
You can actually use @Getter and @Setter lombok annotations to reduce the code size here

2021-07-01 13:12 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/memory/MemoryCard.java
> +                log.info("level = {}", gameInstance.getLevel());
please remove log info if it was used for testing purpose

2021-07-01 13:12 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/memory/MemoryLettersGameLauncher.java
> +
remove empty line

2021-07-02 10:09 UTC, closed without merging