Oui non
GazePlay/GazePlay pull request #1366
Opened 2021-05-19 09:08 UTC by Iluvrog

Add a yes/no game in the opinions game option

2021-05-28 10:05 UTC, PillouMatou requested changes
Translate your buttons
![image](https://user-images.githubusercontent.com/43779207/119967674-e6a84680-bfac-11eb-9f6a-2bf24a57eda8.png)
- maybe remove the bar in the middle of the screen

2021-06-02 12:53 UTC, Iluvrog commented
> Translate your buttons
> ![image](https://user-images.githubusercontent.com/43779207/119967674-e6a84680-bfac-11eb-9f6a-2bf24a57eda8.png)
> 
> * maybe remove the bar in the middle of the screen

translation done and bar remove

2021-06-03 15:26 UTC, PillouMatou approved these changes
it's fine for me @kuhlkrein @schwabdidier

2021-07-02 08:10 UTC, kuhlkrein requested changes

2021-07-02 08:10 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/opinions/OpinionsGame.java
> +            /*List<Image> Picture = thumbImage.pickAllImages();
please remove the useless comments here

2021-07-02 08:10 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/opinions/OpinionsGame.java
> +            if (type.equals(OpinionsGameVariant.ONBH)) {
Please use 'else if' instead of only if to avoid multiple tests

2021-07-02 08:10 UTC, kuhlkrein commented
Somme changes are needed and there are some conflicts in files too :)

2021-07-05 08:21 UTC, Iluvrog commented
> Some changes are needed and there are some conflicts in files too :)

It's done

2021-07-06 10:00 UTC, kuhlkrein approved these changes
Looks good now

2021-07-06 10:00 UTC, merged