Labyrinthe generation aleatoire
GazePlay/GazePlay pull request #1369
Opened 2021-05-20 14:22 UTC by Iluvrog

2021-05-28 09:40 UTC, PillouMatou requested changes
It work fine,
Translate your buttons (file for translate: multilinguism.csv)
![image](https://user-images.githubusercontent.com/43779207/119964245-4b61a200-bfa9-11eb-958c-db69476e4747.png)

2021-06-02 12:35 UTC, Iluvrog commented
> It work fine,
> Translate your buttons (file for translate: multilinguism.csv)
> ![image](https://user-images.githubusercontent.com/43779207/119964245-4b61a200-bfa9-11eb-958c-db69476e4747.png)

Translation done

2021-06-03 15:16 UTC, PillouMatou approved these changes
It's fine for me @schwabdidier @kuhlkrein

2021-07-02 08:31 UTC, kuhlkrein approved these changes

2021-07-02 08:46 UTC, merged