Remove the duration of the fixation in games that do not use the fixation #1368
GazePlay/GazePlay pull request #1375
Opened 2021-05-25 15:12 UTC by Iluvrog

I hope I don't forget a game

2021-05-28 09:11 UTC, PillouMatou requested changes
For the game Spot the differences, there is a fixation on the button at the bottom of the page.

The rest is fine 👍

2021-05-31 08:09 UTC, PillouMatou approved these changes
It's fine for me, @kuhlkrein @schwabdidier

2021-07-02 08:46 UTC, kuhlkrein requested changes

2021-07-02 08:46 UTC, kuhlkrein commented on gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java
> +    public void SetOffFixationLengthControl(){
Please don't use majuscule at the beginning of the function or PMD will detect is as an issue

2021-07-02 08:46 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/moles/Moles.java
> +
remove useless space

2021-07-02 08:46 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/race/Race.java
> +
remove useless space

2021-07-02 08:46 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/shooter/Shooter.java
> +
remove useless space

2021-07-02 12:52 UTC, Iluvrog commented
@kuhlkrein it's done

2021-07-06 15:19 UTC, kuhlkrein commented
please fix the conflicts and it will be fine :)

2021-07-07 07:08 UTC, Iluvrog commented
> please fix the conflicts and it will be fine :)

done

2021-07-07 12:45 UTC, kuhlkrein approved these changes
Looks good to me !

2021-07-07 12:45 UTC, merged