Where is the animal? dynamic variant
GazePlay/GazePlay pull request #1382
Opened 2021-06-28 13:30 UTC by verafili

A new game variant of _Where is the animal?_ game.

Also, there are new graphical statistics for games with dynamic adaptation. Instead of the area chart, information about levels variations during the gameplay is plotted for dynamic variants of Ninja and Memory games. For Where is the animal, a table allows determining if a child's decisions were random or not after every eight rounds depending on the alpha (probability of error).

2021-06-29 07:56 UTC, PillouMatou reviewed
it work well, but why in the game where is the animal we only look for cats?

2021-06-29 07:56 UTC, Noars reviewed
The game work fine but is it normal that we are always asked to find the cat and not another animal?

2021-06-29 07:56 UTC, Noars commented on gazeplay-core/src/main/resources/data/common/table.css
> +}
Need new line at the end of the file

2021-07-01 09:43 UTC, kuhlkrein commented
When the "winner" image is being displayed on fullscreen, it is stretching a lot on the horizontal axis but not on the vertical, it looks like this issue has been fixed for 2*2+ variant but not for the 2*2 (even in normal mode), we need to fix this (maybe in a next PR as it is probably not an error due to your code)

2021-07-02 13:03 UTC, kuhlkrein requested changes
Please try to rebase to not display the "fixation length" commit in this PR

2021-09-16 11:49 UTC, kuhlkrein approved these changes
looks good to me

2021-09-16 11:52 UTC, merged