Dot to dot #1387
GazePlay/GazePlay pull request #1450
Opened 2021-07-28 15:17 UTC by verafili

This new game has two game variants: the classic one where patterns change ramdomely and the dynamic one where the number of dots in patterns increases on each level.

We could add a new game variant where dots are not shown on the screen initially but appear one after another during the game.

2021-09-07 13:49 UTC, kuhlkrein commented
![image](https://user-images.githubusercontent.com/24478346/132356173-b4bac506-bbaf-4ecf-9dba-0385273b493e.png)
![image](https://user-images.githubusercontent.com/24478346/132356192-a7cc0dc8-8866-4654-b2e4-999a7a0f7f98.png)

Dot out of screen

2021-09-07 13:54 UTC, kuhlkrein requested changes

2021-09-07 13:54 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/dottodot/DotToDot.java
> +        for (JsonElement element : elements) {
Please extract some functions to make the code easier to read

2021-09-07 13:54 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/dottodot/DotEntity.java
> +            gameObject.setPrevious(1);
Please remove only the bad one to avoid restarting from the begining

2021-09-07 13:54 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/dottodot/DotEntity.java
> +    public void drawTheLine() {
Could you change the color of the currently selected number, so that it's obvious that we should start from "2", otherwise the user will select 1 and will have no feedback

2021-09-07 13:54 UTC, kuhlkrein commented on gazeplay-games/src/main/java/net/gazeplay/games/dottodot/DotEntity.java
> +    public void drawTheLine() {
maybe you can update the corresponding circle's color

2021-09-10 08:44 UTC, verafili commented
@kuhlkrein suggestions were fixed and also the size of dots is bigger now.

2021-09-13 13:58 UTC, kuhlkrein approved these changes
looks good to me now

2021-09-13 14:12 UTC, merged