[CreamPie] target outside the window #1531
GazePlay/GazePlay pull request #1594
Opened 2022-06-24 08:28 UTC by Karine-Benhaimi

Fix target position in CreamPie game #1531

2022-06-24 08:28 UTC, Karine-Benhaimi commented
Fix target position in CreamPie game #1531

2022-06-27 07:22 UTC, PillouMatou approved these changes
it's fine for me

2022-06-27 07:51 UTC, Noars requested changes

2022-06-27 07:51 UTC, Noars commented on gazeplay-games-commons/src/main/java/net/gazeplay/components/RandomPositionGenerator.java
> +         return createPositionCreamPie(minX, minY, maxX, maxY);
Faire une modification dans cette fonction, oblige tous les autres jeux autres que creampie a quand même utiliser la fonction "createPositionCreampie".
Le mieux a faire est de faire une nouvelle fonction "newRandomBoudedPosition" que tu appelle genre  "newRandomBoudedPositionCreampie", qui elle utilise la fonctione que tu as crée  "createPositionCreamPie".
Et il faudra penser a changer cela aussi dans les class Hand et Target de Creampie.

2022-06-28 07:10 UTC, Noars approved these changes

2022-06-28 07:31 UTC, PillouMatou requested changes
![image](https://user-images.githubusercontent.com/43779207/176120014-c8fc6bf5-6b34-45a5-ab9e-001386c9826f.png)

j'ai testé et je suis tombé sur plusieurs cas comme celui-ci, du coup y a un petit soucis

2022-07-08 08:13 UTC, PillouMatou approved these changes

2022-07-08 08:13 UTC, merged