Sound game#1441
GazePlay/GazePlay pull request #1604
Opened 2022-07-06 09:48 UTC by Karine-Benhaimi

New Game : Which image corresponds to this sound #1441
2 versions :
-Find the sound source
-Guess the animal sound

2022-07-06 09:48 UTC, Karine-Benhaimi commented
New Game : Which image corresponds to this sound https://github.com/GazePlay/GazePlay/issues/1441
2 versions :
-Find the sound source
-Guess the animal sound

2022-07-07 07:50 UTC, PillouMatou requested changes
Il faudrait couper la musique par défaut lorsque que l'on joue à ces jeux, sinon on n'entend pas facilement les sons.

2022-07-07 08:44 UTC, PillouMatou requested changes
il manque la traduction du "listen to the song" quand on lance le jeu

2022-07-08 08:09 UTC, PillouMatou approved these changes

2022-07-08 08:10 UTC, merged